const FETCH_USERS = "FETCH_USERS";
const UPDATE_USER = "UPDATE_USER";
const EXPORT_DATA = "EXPORT_DATA";
const ADD_USERS = "ADD_USERS";

export default { FETCH_USERS, UPDATE_USER, EXPORT_DATA, ADD_USERS };
